services:
  - type: web
    name: MiruroAPI
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://miruro.tv,https://miruro.to,https://miruro.bz,https://miruro.ru
